# Capture Device
CaptureDevice=rnnoise_source
# Model
ModelName=paraformer-zh
# Enable Postprocess (Config: ~/.config/fcitx5/conf/vinput-scenes.json)
LlmEnabled=True
# Endpoint URL
LlmBaseUrl=http://10.0.0.253:3000/v1
# Access Key
LlmApiKey=sk-8iIKa127O12cKQskgMMZXCVjQ3O52dU0NNVY3sUptXtqSEMm
# Postprocess Model
LlmModel=gpt-5.2
# Postprocess Candidate Count
LlmCandidateCount=5
# Request Timeout (ms)
LlmTimeoutMs=60002

[TriggerKey]
0=Control+Control_R

[SceneMenuKey]
0=F9

[PagePrevKeys]
0=Page_Up
1=KP_Page_Up

[PageNextKeys]
0=Next
1=KP_Next

