[colors]
ansi0 = "#282c34"
ansi1 = "#e06c75"
ansi10 = "#98c379"
ansi11 = "#e5c07b"
ansi12 = "#61afef"
ansi13 = "#c678dd"
ansi14 = "#56b6c2"
ansi15 = "#ffffff"
ansi2 = "#98c379"
ansi3 = "#e5c07b"
ansi4 = "#61afef"
ansi5 = "#c678dd"
ansi6 = "#56b6c2"
ansi7 = "#abb2bf"
ansi8 = "#5c6370"
ansi9 = "#e06c75"
aqua = "#56b6c2"
bg = "#282c34"
bg_dim = "#282c34"
blue = "#61afef"
border = "#e5c07b"
border_dim = "#5c6370"
cursor = "#abb2bf"
fg = "#abb2bf"
fg_dim = "#abb2bf"
gray = "#5c6370"
green = "#98c379"
orange = "#e5c07b"
purple = "#c678dd"
red = "#e06c75"
selection = "#5c6370"
yellow = "#e5c07b"
