[theme.custom]
accent = "#61afef"
panel_bg = "#282c34"
surface0 = "#282c34"
surface1 = "#5c6370"
surface_dim = "#23262d"
overlay0 = "#555a64"
overlay1 = "#7d838e"
text = "#abb2bf"
subtext0 = "#abb2bf"
mauve = "#c678dd"
green = "#98c379"
yellow = "#e5c07b"
red = "#e06c75"
blue = "#61afef"
teal = "#56b6c2"
peach = "#e5c07b"
