[theme.custom]
accent = "#7daea3"
panel_bg = "#282828"
surface0 = "#3c3836"
surface1 = "#3c3836"
surface_dim = "#232323"
overlay0 = "#645c4f"
overlay1 = "#978970"
text = "#d4be98"
subtext0 = "#d4be98"
mauve = "#d3869b"
green = "#a9b665"
yellow = "#d8a657"
red = "#ea6962"
blue = "#7daea3"
teal = "#89b482"
peach = "#d8a657"
