# Alacritty terminal configuration
# Theme colors loaded from current theme

[general]
import = ["~/.config/current/alacritty.toml"]

[window]
padding = { x = 15, y = 15 }
decorations = "Full"
opacity = 1.0
dynamic_padding = true

[scrolling]
history = 10000

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono" }
bold = { family = "CaskaydiaMono Nerd Font Mono" }
italic = { family = "CaskaydiaMono Nerd Font Mono" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono" }
size = 10.5

# Font offset for better vertical alignment
[font.offset]
x = 0
y = 2

[cursor]
style = { shape = "Beam", blinking = "On" }

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
