[font]
normal = { family = "CaskaydiaMono Nerd Font Mono" }
bold = { family = "CaskaydiaMono Nerd Font Mono" }
italic = { family = "CaskaydiaMono Nerd Font Mono" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono" }
