[theme.custom]
accent = "#b4637a"
panel_bg = "#faf4ed"
surface0 = "#f2e9e1"
surface1 = "#9893a5"
surface_dim = "#dcd6d0"
overlay0 = "#c0bbc4"
overlay1 = "#908aa1"
text = "#575279"
subtext0 = "#797593"
mauve = "#907aa9"
green = "#286983"
yellow = "#ea9d34"
red = "#b4637a"
blue = "#56949f"
teal = "#d7827e"
peach = "#d18253"
