[colors]
ansi0 = "#494d64"
ansi1 = "#ed8796"
ansi10 = "#a6da95"
ansi11 = "#eed49f"
ansi12 = "#8aadf4"
ansi13 = "#f5bde6"
ansi14 = "#8bd5ca"
ansi15 = "#a5adcb"
ansi2 = "#a6da95"
ansi3 = "#eed49f"
ansi4 = "#8aadf4"
ansi5 = "#f5bde6"
ansi6 = "#8bd5ca"
ansi7 = "#b8c0e0"
ansi8 = "#5b6078"
ansi9 = "#ed8796"
aqua = "#8bd5ca"
bg = "#24273a"
bg_dim = "#494d64"
blue = "#8aadf4"
border = "#eed49f"
border_dim = "#5b6078"
cursor = "#f4dbd6"
fg = "#cad3f5"
fg_dim = "#8087a2"
gray = "#5b6078"
green = "#a6da95"
orange = "#eed49f"
purple = "#f5bde6"
red = "#ed8796"
selection = "#f4dbd6"
yellow = "#eed49f"
