[colors]
ansi0 = "#32344a"
ansi1 = "#f7768e"
ansi10 = "#b9f27c"
ansi11 = "#ff9e64"
ansi12 = "#7da6ff"
ansi13 = "#bb9af7"
ansi14 = "#0db9d7"
ansi15 = "#acb0d0"
ansi2 = "#9ece6a"
ansi3 = "#e0af68"
ansi4 = "#7aa2f7"
ansi5 = "#ad8ee6"
ansi6 = "#449dab"
ansi7 = "#787c99"
ansi8 = "#444b6a"
ansi9 = "#ff7a93"
aqua = "#0db9d7"
bg = "#1a1b26"
bg_dim = "#32344a"
blue = "#7da6ff"
border = "#ff9e64"
border_dim = "#444b6a"
cursor = "#a9b1d6"
fg = "#a9b1d6"
fg_dim = "#a9b1d6"
gray = "#444b6a"
green = "#b9f27c"
orange = "#ff9e64"
purple = "#bb9af7"
red = "#ff7a93"
selection = "#7aa2f7"
yellow = "#ff9e64"
