[theme.custom]
accent = "#7aa2f7"
panel_bg = "#1a1b26"
surface0 = "#32344a"
surface1 = "#444b6a"
surface_dim = "#161721"
overlay0 = "#4c4f63"
overlay1 = "#767c98"
text = "#a9b1d6"
subtext0 = "#787c99"
mauve = "#ad8ee6"
green = "#9ece6a"
yellow = "#e0af68"
red = "#f7768e"
blue = "#7aa2f7"
teal = "#449dab"
peach = "#e0af68"
