[colors]
ansi0 = "#23372B"
ansi1 = "#FF5345"
ansi10 = "#143614"
ansi11 = "#E5C736"
ansi12 = "#ACD4CF"
ansi13 = "#75bbb3"
ansi14 = "#8CD3CB"
ansi15 = "#9eebb3"
ansi2 = "#549e6a"
ansi3 = "#459451"
ansi4 = "#509475"
ansi5 = "#D2689C"
ansi6 = "#2DD5B7"
ansi7 = "#F6F5DD"
ansi8 = "#53685B"
ansi9 = "#db9f9c"
aqua = "#8CD3CB"
bg = "#111c18"
bg_dim = "#23372B"
blue = "#ACD4CF"
border = "#E5C736"
border_dim = "#53685B"
cursor = "#D7C995"
fg = "#C1C497"
fg_dim = "#C1C497"
gray = "#53685B"
green = "#143614"
orange = "#E5C736"
purple = "#75bbb3"
red = "#db9f9c"
selection = "#53685B"
yellow = "#E5C736"
