[theme.custom]
accent = "#2dd5b7"
panel_bg = "#111c18"
surface0 = "#23372b"
surface1 = "#53685b"
surface_dim = "#0e1815"
overlay0 = "#4e5644"
overlay1 = "#83896a"
text = "#c1c497"
subtext0 = "#9a9c78"
mauve = "#d2689c"
green = "#549e6a"
yellow = "#459451"
red = "#ff5345"
blue = "#509475"
teal = "#2dd5b7"
peach = "#e5c736"
