[tools]
android-cli = "latest"
android-sdk = "latest"
aube = "latest"
codex = "latest"
gh = "latest"
"github:bluenviron/mediamtx" = "latest"
"github:go-musicfox/go-musicfox" = "latest"
"github:iOfficeAI/OfficeCLI" = "latest"
"github:zibo-chen/newbee-ocr-cli" = "latest"
go = "latest"
gradle = "latest"
java = "latest"
lefthook = "latest"
node = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"npm:@jackwener/opencli" = "latest"
"npm:skills" = "latest"
pi = "latest"
"pipx:pioarduino" = "latest"
"pipx:yt-dlp" = { version = "latest", uvx_args = "--with secretstorage" }
shfmt = "3.13.1"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age = "0s"
use_versions_host = false

[settings.github]
credential_command = "gh auth token"
