# Allow non-root users to control Intel GPU frequency limits
z /sys/class/drm/card1/gt_min_freq_mhz 0666 root root - -
z /sys/class/drm/card1/gt_max_freq_mhz 0666 root root - -
z /sys/class/drm/card1/gt_boost_freq_mhz 0666 root root - -
