# Main user configuration for ftty terminal emulator
# Managed by arch-post-install

include = ["~/.local/state/theme/ftty.toml"]

[font]
family = ["JetBrainsMono Nerd Font", "Sarasa Mono SC", "Noto Color Emoji"]

[window]
padding = [8, 6]
