[colors]
ansi0 = "#72696a"
ansi1 = "#fd6883"
ansi10 = "#c8e292"
ansi11 = "#fcd675"
ansi12 = "#f8a788"
ansi13 = "#bebffd"
ansi14 = "#9bf1e1"
ansi15 = "#f1e5e7"
ansi2 = "#adda78"
ansi3 = "#f9cc6c"
ansi4 = "#f38d70"
ansi5 = "#a8a9eb"
ansi6 = "#85dacc"
ansi7 = "#e6d9db"
ansi8 = "#948a8b"
ansi9 = "#ff8297"
aqua = "#9bf1e1"
bg = "#2c2525"
bg_dim = "#72696a"
blue = "#f8a788"
border = "#fcd675"
border_dim = "#948a8b"
cursor = "#c3b7b8"
fg = "#e6d9db"
fg_dim = "#e6d9db"
gray = "#948a8b"
green = "#c8e292"
orange = "#fcd675"
purple = "#bebffd"
red = "#ff8297"
selection = "#403e41"
yellow = "#fcd675"
