[theme.custom]
accent = "#a8a9eb"
panel_bg = "#2c2525"
surface0 = "#72696a"
surface1 = "#948a8b"
surface_dim = "#262020"
overlay0 = "#6d6464"
overlay1 = "#a49a9b"
text = "#e6d9db"
subtext0 = "#e6d9db"
mauve = "#a8a9eb"
green = "#adda78"
yellow = "#f9cc6c"
red = "#fd6883"
blue = "#f38d70"
teal = "#85dacc"
peach = "#f9cc6c"
