#!/bin/sh
# River modes - advanced keybinding modes
# Inspired by nate zhou's config

mod="Mod4"  # Super/Windows key

# Resize mode ################################################################
# Press Super+Ctrl+R to enter resize mode
# In resize mode:
#   - hjkl: move floating window
#   - yuio: resize window (y=shrink width, u=grow height, i=shrink height, o=grow width)
#   - f: toggle float
#   - Escape/Space/Super+Ctrl+R: exit mode

riverctl declare-mode resize
riverctl map normal ${mod}+Control r enter-mode resize

riverctl map resize ${mod}+Control r    enter-mode normal
riverctl map resize None           Escape  enter-mode normal
riverctl map resize None           space   enter-mode normal

riverctl map -repeat resize None f toggle-float

# Move floating window
riverctl map -repeat resize None h move left 50
riverctl map -repeat resize None j move down 50
riverctl map -repeat resize None k move up 50
riverctl map -repeat resize None l move right 50

# Resize window
riverctl map -repeat resize None y resize horizontal -50
riverctl map -repeat resize None u resize vertical 50
riverctl map -repeat resize None i resize vertical -50
riverctl map -repeat resize None o resize horizontal 50
