[colors]
ansi0 = "#bcc0cc"
ansi1 = "#d20f39"
ansi10 = "#40a02b"
ansi11 = "#df8e1d"
ansi12 = "#1e66f5"
ansi13 = "#ea76cb"
ansi14 = "#179299"
ansi15 = "#6c6f85"
ansi2 = "#40a02b"
ansi3 = "#df8e1d"
ansi4 = "#1e66f5"
ansi5 = "#ea76cb"
ansi6 = "#179299"
ansi7 = "#5c5f77"
ansi8 = "#acb0be"
ansi9 = "#d20f39"
aqua = "#179299"
bg = "#eff1f5"
bg_dim = "#bcc0cc"
blue = "#1e66f5"
border = "#df8e1d"
border_dim = "#acb0be"
cursor = "#dc8a78"
fg = "#4c4f69"
fg_dim = "#8c8fa1"
gray = "#acb0be"
green = "#40a02b"
orange = "#df8e1d"
purple = "#ea76cb"
red = "#d20f39"
selection = "#dc8a78"
yellow = "#df8e1d"
