[theme.custom]
accent = "#8839ef"
panel_bg = "#eff1f5"
surface0 = "#bcc0cc"
surface1 = "#acb0be"
surface_dim = "#d2d4d7"
overlay0 = "#b5b8c4"
overlay1 = "#85879a"
text = "#4c4f69"
subtext0 = "#8c8fa1"
mauve = "#ea76cb"
green = "#40a02b"
yellow = "#df8e1d"
red = "#d20f39"
blue = "#1e66f5"
teal = "#179299"
peach = "#d95429"
