[colors]
ansi0 = "#090618"
ansi1 = "#c34043"
ansi10 = "#98bb6c"
ansi11 = "#e6c384"
ansi12 = "#7fb4ca"
ansi13 = "#938aa9"
ansi14 = "#7aa89f"
ansi15 = "#dcd7ba"
ansi2 = "#76946a"
ansi3 = "#c0a36e"
ansi4 = "#7e9cd8"
ansi5 = "#957fb8"
ansi6 = "#6a9589"
ansi7 = "#c8c093"
ansi8 = "#727169"
ansi9 = "#e82424"
aqua = "#7aa89f"
bg = "#1f1f28"
bg_dim = "#090618"
blue = "#7fb4ca"
border = "#e6c384"
border_dim = "#727169"
cursor = "#dcd7ba"
fg = "#dcd7ba"
fg_dim = "#dcd7ba"
gray = "#727169"
green = "#98bb6c"
orange = "#e6c384"
purple = "#938aa9"
red = "#e82424"
selection = "#2d4f67"
yellow = "#e6c384"
