[theme.custom]
accent = "#7e9cd8"
panel_bg = "#1f1f28"
surface0 = "#090618"
surface1 = "#727169"
surface_dim = "#1b1b23"
overlay0 = "#615f5b"
overlay1 = "#999686"
text = "#dcd7ba"
subtext0 = "#c8c093"
mauve = "#957fb8"
green = "#76946a"
yellow = "#c0a36e"
red = "#c34043"
blue = "#7e9cd8"
teal = "#6a9589"
peach = "#c0a36e"
