#!/bin/sh
# River init - minimal config

mod="Mod4"

# Autostart
riverctl spawn waybar
riverctl spawn "fcitx5 -d"

# Keybindings
riverctl map normal $mod Return spawn foot                    # Super+Enter: terminal
riverctl map normal $mod Space spawn "wofi --show drun"      # Super+Space: launcher
riverctl map normal $mod B spawn firefox                      # Super+B: browser
riverctl map normal $mod F spawn pcmanfm                      # Super+F: file manager
riverctl map normal $mod C spawn code                         # Super+C: vscode

riverctl map normal $mod+Shift Q close                        # Super+Shift+Q: close window
riverctl map normal $mod W close                              # Super+W: close window
riverctl map normal $mod+Shift E exit                         # Super+Shift+E: exit river

# Layout
riverctl default-layout rivertile
rivertile &
