# Auto-generated by x-theme template pipeline
# Theme: Current Desktop Palette

# Main bg
theme[main_bg]="{{ background }}"

# Main text color
theme[main_fg]="{{ foreground }}"

# Title color for boxes
theme[title]="{{ foreground }}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{ accent }}"

# Background color of selected item in processes box
theme[selected_bg]="{{ selection }}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{ foreground }}"

# Color of inactive/disabled text
theme[inactive_fg]="{{ muted }}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{ accent }}"

# Box outline and divider colors
theme[cpu_box]="{{ muted }}"
theme[mem_box]="{{ muted }}"
theme[net_box]="{{ muted }}"
theme[proc_box]="{{ muted }}"
theme[div_line]="{{ muted }}"

# Temperature graph colors
theme[temp_start]="{{ green }}"
theme[temp_mid]="{{ yellow }}"
theme[temp_end]="{{ red }}"

# CPU graph colors
theme[cpu_start]="{{ green }}"
theme[cpu_mid]="{{ yellow }}"
theme[cpu_end]="{{ red }}"

# Mem/Disk free meter
theme[free_start]="{{ green }}"
theme[free_mid]="{{ yellow }}"
theme[free_end]="{{ red }}"

# Mem/Disk cached meter
theme[cached_start]="{{ green }}"
theme[cached_mid]="{{ yellow }}"
theme[cached_end]="{{ red }}"

# Mem/Disk available meter
theme[available_start]="{{ green }}"
theme[available_mid]="{{ yellow }}"
theme[available_end]="{{ red }}"

# Mem/Disk used meter
theme[used_start]="{{ green }}"
theme[used_mid]="{{ yellow }}"
theme[used_end]="{{ red }}"

# Download graph colors
theme[download_start]="{{ green }}"
theme[download_mid]="{{ yellow }}"
theme[download_end]="{{ red }}"

# Upload graph colors
theme[upload_start]="{{ green }}"
theme[upload_mid]="{{ yellow }}"
theme[upload_end]="{{ red }}"
