# -*- conf -*-
# Fnott notification daemon theme (Suckless direct-angle typography & geometry)
# Auto-generated by custom-theme: DO NOT EDIT DIRECTLY

# Global geometry and placement
layer=overlay
anchor=top-right
stacking-order=bottom-up
min-width=360
max-width=360
max-height=150
edge-margin-vertical=16
edge-margin-horizontal=16
notification-margin=6
border-size=2
border-radius=0
padding-vertical=10
padding-horizontal=12
max-icon-size=48
icon-theme=Adwaita

# Formatting (hide process/application name, keep clean summary & body)
title-format=
summary-format=<b>%s</b>\n
body-format=%b

# Global color scheme
background={{ background_strip }}f0
border-color={{ accent_strip }}ff
title-color={{ bright_foreground_strip }}ff
summary-color={{ bright_foreground_strip }}ff
body-color={{ light_foreground_strip }}ff
progress-color={{ accent_strip }}ff

# Timeout defaults (seconds)
default-timeout=6
idle-timeout=0

[low]
background={{ background_strip }}f0
border-color={{ muted_strip }}ff
title-color={{ muted_strip }}ff
summary-color={{ muted_strip }}ff
body-color={{ muted_strip }}ff
default-timeout=3

[normal]
background={{ background_strip }}f0
border-color={{ accent_strip }}ff
title-color={{ bright_foreground_strip }}ff
summary-color={{ bright_foreground_strip }}ff
body-color={{ light_foreground_strip }}ff
default-timeout=6

[critical]
background={{ background_strip }}f0
border-color={{ red_strip }}ff
title-color={{ bright_red_strip }}ff
summary-color={{ bright_red_strip }}ff
body-color={{ bright_red_strip }}ff
default-timeout=12
