# ftty terminal emulator theme
# Auto-generated by custom-theme: DO NOT EDIT DIRECTLY

[colors]
foreground = "{{ foreground }}"
background = "{{ background }}"
black = "{{ dark_background }}"
red = "{{ red }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
blue = "{{ blue }}"
magenta = "{{ magenta }}"
cyan = "{{ cyan }}"
white = "{{ foreground }}"
bright_black = "{{ muted }}"
bright_red = "{{ bright_red }}"
bright_green = "{{ bright_green }}"
bright_yellow = "{{ bright_yellow }}"
bright_blue = "{{ bright_blue }}"
bright_magenta = "{{ bright_magenta }}"
bright_cyan = "{{ bright_cyan }}"
bright_white = "{{ bright_foreground }}"
