# Auto-generated by custom-theme from active theme
$bg = rgb({{ background_strip }})
$fg = rgb({{ foreground_strip }})
$accent = rgb({{ accent_strip }})
$muted = rgb({{ muted_strip }})
$red = rgb({{ red_strip }})
$selection = rgb({{ selection_strip }})
