# Mako notification daemon theme (Suckless direct-angle typography & geometry)
# Auto-generated by x-theme: DO NOT EDIT DIRECTLY

font=Sarasa Mono SC 10
width=360
height=150
layer=overlay
outer-margin=16,16
margin=0,0,6,0
padding=10,12
border-size=2
border-radius=0
icons=1
max-icon-size=48
icon-location=left

background-color={{ background }}
text-color={{ foreground }}
border-color={{ accent }}
progress-color=over {{ accent }}

format=<b>%s</b>\n%b

default-timeout=6000
ignore-timeout=0

[urgency=low]
border-color={{ muted }}
default-timeout=3000

[urgency=high]
border-color={{ red }}
text-color={{ red }}
default-timeout=0
