-- Auto-generated by arch-theme-set from active theme
return {
  colors = {
    foreground = "{{ foreground }}",
    background = "{{ background }}",
    cursor_bg = "{{ bright_foreground }}",
    cursor_fg = "{{ background }}",
    cursor_border = "{{ bright_foreground }}",
    selection_fg = "{{ background }}",
    selection_bg = "{{ selection }}",
    compose_cursor = "{{ accent }}",
    ansi = {
      "{{ dark_background }}",
      "{{ red }}",
      "{{ green }}",
      "{{ yellow }}",
      "{{ blue }}",
      "{{ magenta }}",
      "{{ cyan }}",
      "{{ foreground }}",
    },
    brights = {
      "{{ dark_foreground }}",
      "{{ bright_red }}",
      "{{ bright_green }}",
      "{{ bright_yellow }}",
      "{{ bright_blue }}",
      "{{ bright_magenta }}",
      "{{ bright_cyan }}",
      "{{ bright_foreground }}",
    },
    tab_bar = {
      background = "{{ background }}",
      active_tab = {
        bg_color = "{{ accent }}",
        fg_color = "{{ background }}",
      },
      inactive_tab = {
        bg_color = "{{ dark_background }}",
        fg_color = "{{ foreground }}",
      },
      inactive_tab_hover = {
        bg_color = "{{ dark_background }}",
        fg_color = "{{ accent }}",
      },
      new_tab = {
        bg_color = "{{ background }}",
        fg_color = "{{ foreground }}",
      },
      new_tab_hover = {
        bg_color = "{{ dark_background }}",
        fg_color = "{{ accent }}",
      },
    },
  },
}
