[colors]
ansi0 = "#3b4252"
ansi1 = "#bf616a"
ansi10 = "#a3be8c"
ansi11 = "#ebcb8b"
ansi12 = "#81a1c1"
ansi13 = "#b48ead"
ansi14 = "#8fbcbb"
ansi15 = "#eceff4"
ansi2 = "#a3be8c"
ansi3 = "#ebcb8b"
ansi4 = "#81a1c1"
ansi5 = "#b48ead"
ansi6 = "#88c0d0"
ansi7 = "#e5e9f0"
ansi8 = "#4c566a"
ansi9 = "#bf616a"
aqua = "#8fbcbb"
bg = "#2e3440"
bg_dim = "#3b4252"
blue = "#81a1c1"
border = "#ebcb8b"
border_dim = "#4c566a"
cursor = "#d8dee9"
fg = "#d8dee9"
fg_dim = "#a5abb6"
gray = "#4c566a"
green = "#a3be8c"
orange = "#ebcb8b"
purple = "#b48ead"
red = "#bf616a"
selection = "#4c566a"
yellow = "#ebcb8b"
