[theme.custom]
accent = "#88c0d0"
panel_bg = "#2e3440"
surface0 = "#3b4252"
surface1 = "#4c566a"
surface_dim = "#282d38"
overlay0 = "#696f7b"
overlay1 = "#9ca2ad"
text = "#d8dee9"
subtext0 = "#a5abb6"
mauve = "#b48ead"
green = "#a3be8c"
yellow = "#ebcb8b"
red = "#bf616a"
blue = "#81a1c1"
teal = "#88c0d0"
peach = "#d79b7c"
