[colors]
ansi0 = "#333333"
ansi1 = "#D35F5F"
ansi10 = "#FFC107"
ansi11 = "#b90a0a"
ansi12 = "#f59e0b"
ansi13 = "#B91C1C"
ansi14 = "#eaeaea"
ansi15 = "#ffffff"
ansi2 = "#FFC107"
ansi3 = "#b91c1c"
ansi4 = "#e68e0d"
ansi5 = "#D35F5F"
ansi6 = "#bebebe"
ansi7 = "#bebebe"
ansi8 = "#8a8a8d"
ansi9 = "#B91C1C"
aqua = "#eaeaea"
bg = "#121212"
bg_dim = "#333333"
blue = "#f59e0b"
border = "#b90a0a"
border_dim = "#8a8a8d"
cursor = "#eaeaea"
fg = "#bebebe"
fg_dim = "#8a8a8d"
gray = "#8a8a8d"
green = "#FFC107"
orange = "#b90a0a"
purple = "#B91C1C"
red = "#B91C1C"
selection = "#333333"
yellow = "#b90a0a"
