[theme.custom]
accent = "#e68e0d"
panel_bg = "#121212"
surface0 = "#333333"
surface1 = "#8a8a8d"
surface_dim = "#0f0f0f"
overlay0 = "#4e4e4e"
overlay1 = "#818181"
text = "#bebebe"
subtext0 = "#8a8a8d"
mauve = "#d35f5f"
green = "#ffc107"
yellow = "#b91c1c"
red = "#d35f5f"
blue = "#e68e0d"
teal = "#bebebe"
peach = "#b90a0a"
