[colors]
[colors.primary]
background = "0xfafafa"
foreground = "0x383a42"

[colors.normal]
black = "0x383a42"
red = "0xe45649"
green = "0x50a14f"
yellow = "0xc18401"
blue = "0x4078f2"
magenta = "0xa626a4"
cyan = "0x0184bc"
white = "0xfafafa"

[colors.bright]
black = "0xa0a1a7"
red = "0xe45649"
green = "0x50a14f"
yellow = "0xc18401"
blue = "0x4078f2"
magenta = "0xa626a4"
cyan = "0x0184bc"
white = "0xffffff"
