[theme.custom]
accent = "#4078f2"
panel_bg = "#fafafa"
surface0 = "#383a42"
surface1 = "#a0a1a7"
surface_dim = "#dcdcdc"
overlay0 = "#b6b6b9"
overlay1 = "#7b7d82"
text = "#383a42"
subtext0 = "#2c2e34"
mauve = "#a626a4"
green = "#50a14f"
yellow = "#c18401"
red = "#e45649"
blue = "#4078f2"
teal = "#0184bc"
peach = "#d06f21"
