[title]
text = Github:xifan233 项目: fcitx5-vinput
font_family = sans-serif
font_size = 42
font_weight = 700
text_color = #ffffff
background = rgba(0, 0, 0, 0.55)
anchor_x = left
anchor_y = top
margin_x = 383
margin_y = 25
