[colors]
ansi0 = "#475258"
ansi1 = "#e67e80"
ansi10 = "#a7c080"
ansi11 = "#dbbc7f"
ansi12 = "#7fbbb3"
ansi13 = "#d699b6"
ansi14 = "#83c092"
ansi15 = "#d3c6aa"
ansi2 = "#a7c080"
ansi3 = "#dbbc7f"
ansi4 = "#7fbbb3"
ansi5 = "#d699b6"
ansi6 = "#83c092"
ansi7 = "#d3c6aa"
ansi8 = "#475258"
ansi9 = "#e67e80"
aqua = "#83c092"
bg = "#2d353b"
bg_dim = "#475258"
blue = "#7fbbb3"
border = "#dbbc7f"
border_dim = "#475258"
cursor = "#d3c6aa"
fg = "#d3c6aa"
fg_dim = "#d3c6aa"
gray = "#475258"
green = "#a7c080"
orange = "#dbbc7f"
purple = "#d699b6"
red = "#e67e80"
selection = "#475258"
yellow = "#dbbc7f"
