[theme.custom]
accent = "#7fbbb3"
panel_bg = "#2d353b"
surface0 = "#475258"
surface1 = "#475258"
surface_dim = "#272e33"
overlay0 = "#676761"
overlay1 = "#989383"
text = "#d3c6aa"
subtext0 = "#d3c6aa"
mauve = "#d699b6"
green = "#a7c080"
yellow = "#dbbc7f"
red = "#e67e80"
blue = "#7fbbb3"
teal = "#83c092"
peach = "#dbbc7f"
